name: activity-cliffs
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - tqdm
  - rdkit
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pip:
      - typer>=0.12

